### ISSUE TITLE
docker agent doesn't connect with docker compose?

### ISSUE THREAD

**Issue by Data-drone** [gocd/docker-gocd-agent#40]
I am using the alpine agent and connecting by using ansible to trigger the compose script to deploy to docker swarm:

```
version: '3'

services:

    go_agent:
      image: gocd/gocd-agent-alpine-3.5:v17.8.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - GO_SERVER_URL=https://http://10.240.226.19:8154/go
```

This is not connecting to the Go server?
However running the agent locally works?

`docker run -d -e GO_SERVER_URL=https://10.240.226.19:8154/go gocd/gocd-agent-alpine-3.5:v17.8.0
`

Thanks
